version: '3.9'

services:

  auth-service:
    build:
      context: ./src
      dockerfile: services/Auth/Auth/Dockerfile
    depends_on:
      - auth-service-db
    container_name: auth-service
    ports:
      - "5201:8080"
    environment:
      - GRPC_PORT=8080
      - AuthDatabase__Password=${AuthDatabase__Password}
      - AccessTokenOptions__SecretKey=${AccessTokenOptions__SecretKey}

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      - POSTGRES_DB=auth-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${AuthDatabasePassword} 
    ports:
      - "5400:5432"
    volumes:
      - auth-service-db:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ./src
      dockerfile: services/ApiGateway/Dockerfile
    container_name: api-gateway
    environment:
      - HTTP_PORT=5108
      - AUTH_ADDRESS=http://auth-service:8080
      - AuthOptions__SecretKey=${AccessTokenOptions__SecretKey}
    ports:
      - "5202:5108"

  auth-bot:
    build:
      context: ./src
      dockerfile: services/AuthBot/Dockerfile
    container_name: auth-bot
    environment:
      - BOT_TOKEN=${BotApiToken}
      - AUTH_ADDRESS=http://auth-service:8080
    ports:
      - "5203:8080"

volumes:
  auth-service-db:
    name: auth-service-db
